Parameters:
  AccountName:
    Description: AWS AccountName
    Type: String
  SlackWebhookUrl:
    Description: Slack WebhookURL
    Type: String
  SlackChannel:
    Description: Slack Channel
    Type: String
  SlackUsername:
    Description: Slack Username
    Type: String
    Default: ""
  SlackIconEmoji:
    Description: Slack IconEmoji
    Type: String
    Default: ""
  ScheduleExpression:
    Description: cron expression
    Type: String
    Default: "cron(0 0 ? * MON *)"

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: GetCostAndUsage
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                Resource:
                  - !Sub "arn:aws:ce:us-east-1:${AWS::AccountId}:/GetCostAndUsage"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws-cost-weekly-notificator
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        ZipFile: |
          const WeeklyCostNotify = require("WeeklyCostNotify");
          exports.handler = async () => { await WeeklyCostNotify() };
      Layers:
        - "arn:aws:lambda:ap-northeast-1:987241170645:layer:aws-cost-notifier:9"
      Environment:
        Variables:
          ACCOUNT_NAME: !Ref AccountName
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
          SLACK_CHANNEL: !Ref SlackChannel
          SLACK_USERNAME: !Ref SlackUsername
          SLACK_ICON_EMOJI: !Ref SlackIconEmoji

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      Name: aws-cost-notifier-rule
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: LambdaFunction
