Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: GetCostAndUsage
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                Resource:
                  - !Sub "arn:aws:ce:us-east-1:${AWS::AccountId}:/GetCostAndUsage"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws-cost-weekly-notificator
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        ZipFile: |
          const WeeklyCostNotify = require("WeeklyCostNotify");
          exports.handler = async () => { await WeeklyCostNotify() };
      Layers:
        - "arn:aws:lambda:ap-northeast-1:987241170645:layer:aws-cost-notifier:8"
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: "<Edit Here>"
          SLACK_CHANNEL: "<Edit Here>"
          SLACK_USERNAME: "opsコストお知らせくん"
          SLACK_ICON_EMOJI: ":money_with_wings:"

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      Name: aws-cost-notifier-rule
      ScheduleExpression: "cron(0 0 ? * MON *)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: LambdaFunction
